apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tts
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - tts-web-service.yaml
  - tts-kokoro-serviceaccount.yaml
  - tts-kokoro-deployment.yaml
  - tts-kokoro-service.yaml
  - instrumentation.yaml
  - servicemonitor-web.yaml
  - servicemonitor-kokoro.yaml
  - prometheusrule.yaml
labels:
  - pairs:
      app.kubernetes.io/managed-by: kubectl
    includeSelectors: false
